name: Build and Push Docker Image

on:
  push:
    branches:
      - varun

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../Strapi-app  # your Dockerfile path

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.varunchavda78 }}
          password: ${{ secrets.aatma@13579 }}

      - name: Extract Git SHA
        id: vars
        run: echo "TAG=latest-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: docker build -t ${{ secrets.varunchavda78 }}/strapi-app:${{ steps.vars.outputs.TAG }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.varunchavda78 }}/strapi-app:${{ steps.vars.outputs.TAG }}

      - name: Save Image Tag
        id: image_tag
        run: echo "tag=${{ steps.vars.outputs.TAG }}" >> $GITHUB_OUTPUT

      - name: Upload Image Tag Artifact
        uses: actions/upload-artifact@v3
        with:
          name: image-tag
          path: ./Strapi-app/image-tag.txt
