name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract Git SHA
        id: vars
        run: echo "TAG=latest-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/strapi-app-cd1:${{ steps.vars.outputs.TAG }} ./Strapi-app

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/strapi-app-cd1:${{ steps.vars.outputs.TAG }}

      - name: Save Image Tag to File
        run: echo "${{ steps.vars.outputs.TAG }}" > image-tag.txt

      - name: Upload Image Tag Artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: image-tag.txt
