name: Terraform Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag
          path: .  # ✅ download to current directory

      - name: Read image tag
        id: image_tag
        run: echo "tag=$(cat image-tag.txt)" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: Terraform1/
        run: terraform init

      - name: Apply Terraform
        working-directory: Terraform1/
        run: terraform apply -auto-approve -var="image_tag=${{ steps.image_tag.outputs.tag }}"
