name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  contents: read
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: Terraform1/
        run: terraform init

      - name: Terraform Action - Apply or Destroy
        working-directory: Terraform1/
        run: |
          if [ "${{ github.event.inputs.action }}" = "apply" ]; then
            terraform apply -auto-approve \
              -var="image_tag=latest" \
              -var="ami_id=ami-0d1b5a8c13042c939" \
              -var="key_name=strapii-key" \
              -var="aws_region=us-east-2" \
              -var="instance_type=t2.micro"
          else
            terraform destroy -auto-approve \
              -var="image_tag=latest" \
              -var="ami_id=ami-0d1b5a8c13042c939" \
              -var="key_name=strapii-key" \
              -var="aws_region=us-east-2" \
              -var="instance_type=t2.micro"
          fi
